name: Bot Cofrade - Cada 5 Minutos

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create .env from Secrets
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env
          echo "DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env
          echo "NEWS_RSS_URL=${{ secrets.NEWS_RSS_URL }}" >> .env
          echo "GIST_URL=${{ secrets.GIST_URL }}" >> .env
          echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> .env

      - name: Run Main Bot
        run: python src/main_bot.py
